steps:
- name: 'gcr.io/cloudbuild/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/flask-app:latest', '.']
  timeout: '1200s'
- name: 'gcr.io/cloudbuild/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/flask-app:latest']
  timeout: '1200s'

