steps:
- name: 'gcr.io/cloudbuild/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/<your-project-id>/<your-repo>/flask-app:latest', '.']
  timeout: '1200s'
- name: 'gcr.io/cloudbuild/docker'
  args: ['push', 'us-central1-docker.pkg.dev/<your-project-id>/<your-repo>/flask-app:latest']
  timeout: '1200s'

