steps:
- name: 'gcr.io/cloudbuild/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/rd-server-391203/cloudrun-docker-sample/flask-app:latest', '.']
  timeout: '1200s'
- name: 'gcr.io/cloudbuild/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/rd-server-391203/cloudrun-docker-sample/flask-app:latest']
  timeout: '1200s'

